configuration:
    - Debug
    - Release

platform:
    - x64

environment:
  matrix:
    # - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    #   GENERATOR: "Visual Studio 15 2017 Win64"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu1804
      GENERATOR: "Unix Makefiles"

init:
  - cmd: SET PATH=C:\Python37-x64\Scripts\;%PATH%
  - sh: sudo apt-get update
  - sh: sudo apt-get -y install python3-pip


install: 
  - cmd: pip3 install conan
  - sh: sudo pip3 install conan
  - conan remote add catchorg https://api.bintray.com/conan/catchorg/Catch2  

before_build:
  - mkdir build
  - cd build
  - cmd: conan install .. -s build_type=%CONFIGURATION%
  - sh: conan install .. -s build_type=$CONFIGURATION -s compiler.libcxx=libstdc++11
  
build_script:
  - conan build ..

#changing into folder to suppress errorcode by failed ctest
test_script:
  - ps: ctest --build-config "$env:CONFIGURATION" -VV
after_test:
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: Get-ChildItem -Path ./ -Filter *.xml -File -Name -Recurse | ForEach-Object {$wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path ./$_))}
